In [1]:
import numpy as np
from sklearn.cluster import KMeans
from keras.datasets import mnist
from sklearn.preprocessing import MinMaxScaler

#set random seed
#np.random.seed(42)

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#reshape data to be 2D
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)

#ensure it's float32
X_train = X_train.astype("float32")
X_test = X_test.astype("float32")

#scale values to be between 0 and 1
X_train = X_train / 255.0
X_test = X_test / 255.0

In [3]:
kmeans = KMeans(n_clusters=10, algorithm='elkan').fit(X_train)
y_pred = kmeans.predict(X_test)


In [4]:
def retrieve_info(cluster_labels,y_train):
    """
    Associates most probable label with each cluster in KMeans model
    returns: dictionary of clusters assigned to each label
    """
    # Initializing
    reference_labels = {}
    # For loop to run through each label of cluster label
    for i in range(len(np.unique(kmeans.labels_))):
        index = np.where(cluster_labels == i,1,0)
        num = np.bincount(y_train[index==1]).argmax()
        reference_labels[i] = num
    return reference_labels

reference_labels = retrieve_info(kmeans.labels_,y_train)

#initialize new y_pred that will hold the correct label names
number_labels = np.random.rand(len(kmeans.labels_))

#switch to correct labels
for i in range(len(kmeans.labels_)):
    number_labels[i] = reference_labels[kmeans.labels_[i]]


print(number_labels[:20].astype('int'))
print(y_train[:20])

from sklearn.metrics import accuracy_score
print(accuracy_score(number_labels,y_train))

# import pandas as pd
# test_pred = np.concatenate((y_test.reshape(y_test.shape[0], 1), y_pred.reshape(y_pred.shape[0], 1)), axis=1)
# test_pred = pd.DataFrame(test_pred,columns=['test', 'prediction'])

# #display(test_pred.value_counts()[:20])

# matrix = [[0 for i in range(10)] for i in range(10)]

# for x in range(10):
#     x_index = x
#     tmp = test_pred[test_pred['test'] == x].value_counts()
#     for y in range(10):
#         try:
#             value = tmp.iloc[y]
#             y_index = tmp.index[y][1]
#         except IndexError:
#             value = 0
#         matrix[x_index][y_index] = value

# #display(matrix)

# from munkres import Munkres, print_matrix
# import sys

# m = Munkres()
# cost_matrix = []
# for row in matrix:
#     cost_row = []
#     for col in row:
#         cost_row += [sys.maxsize - col]
#     cost_matrix += [cost_row]

# m = Munkres()
# indexes = m.compute(cost_matrix)
# #print_matrix(matrix, msg='Highest profit through this matrix:')
# total = 0
# for row, column in indexes:
#     value = matrix[row][column]
#     total += value
#     #print(f'({row}, {column}) -> {value}')

# print('accuracy of k_means {} '.format(total / 10000))



[8 0 4 1 7 2 1 8 1 7 3 1 3 6 1 7 2 8 6 7]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
0.5827


In [85]:
import umap

# X_train = X_train[:5000]
# X_test = X_test[:100]
# y_test = y_test[:100]


#initialize UMAP object
reducer = umap.UMAP(n_components=100)

#create embedded dataset
reducer.fit(X_train)
X_train_emb = reducer.transform(X_train)
X_test_emb = reducer.transform(X_test)
print('Embedding done')

# scaler_emb = MinMaxScaler()
# scaler_emb.fit(X_train_emb)
# X_train_emb = scaler_emb.transform(X_train_emb)
# X_test_emb = scaler_emb.transform(X_test_emb)
# print('Scaling done')

#X = np.vstack((X_train_emb, X_test_emb))
#standardized_X = scaler.fit_transform(X)
#X_train_emb = standardized_X[:X_train_emb.shape[0]]
#X_test_emb = standardized_X[X_train_emb.shape[0]:]

print(X_train_emb.shape)
print(X_test_emb.shape)

print(X_train_emb[5])
print(X_test_emb[3])

print(X_train_emb.min())
print(X_train_emb.max())


KeyboardInterrupt: 

In [79]:
kmeans = KMeans(n_clusters=10, algorithm='elkan').fit(X_train_emb)
y_pred = kmeans.predict(X_test_emb)

In [80]:
reference_labels = retrieve_info(kmeans.labels_,y_train)
number_labels = np.random.rand(len(kmeans.labels_))
for i in range(len(kmeans.labels_)):
  number_labels[i] = reference_labels[kmeans.labels_[i]]

print(number_labels[:20].astype('int'))
print(y_train[:20])

from sklearn.metrics import accuracy_score
print(accuracy_score(number_labels,y_train))



[5 0 4 1 4 2 1 3 1 4 3 5 3 6 1 7 2 8 6 7]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
0.8583833333333334


FileNotFoundError: [Errno 2] No such file or directory: 'coil-20-proc//obj1__0.png'